package com.persiawar2d;

import android.content.Context;import android.graphics.Bitmap;import android.graphics.BitmapFactory;import android.opengl.GLES20;import android.opengl.GLSurfaceView;import android.opengl.GLUtils;import android.opengl.Matrix;import android.view.MotionEvent;import java.io.ByteArrayOutputStream;import java.io.InputStream;import java.nio.ByteBuffer;import java.nio.ByteOrder;import java.nio.FloatBuffer;import java.util.ArrayList;import java.util.zip.ZipEntry;import java.util.zip.ZipInputStream;import javax.microedition.khronos.egl.EGLConfig;import javax.microedition.khronos.opengles.GL10;

public final class AdvancedThreeDRenderer implements GLSurfaceView.Renderer {
 private final Context context;private final ArrayList<Building> buildings=new ArrayList<>();private final ArrayList<Integer> textures=new ArrayList<>();private final ArrayList<Bitmap> pending=new ArrayList<>();private final float[] p=new float[16],v=new float[16],vp=new float[16],m=new float[16],mm=new float[16];private FloatBuffer cube,quad,uv;private int cp,cc,cm,tp,tu,tm,ts,pc,pt;private float px=0,pz=18,yaw,dx,dy,lx;private boolean move;
 public AdvancedThreeDRenderer(Context c){context=c;load();for(int z=-30;z<=30;z+=10)for(int x=-30;x<=30;x+=10)if(Math.abs(x)>7||Math.abs(z)>7)buildings.add(new Building(x,z,5,5,2.5f+(buildings.size()%3)*.8f,buildings.size()));}
 private void load(){try(InputStream in=context.getAssets().open("original_packages/kenney_isometric-buildings.zip");ZipInputStream z=new ZipInputStream(in)){ZipEntry e;while((e=z.getNextEntry())!=null&&pending.size()<16){String n=e.getName().toLowerCase();if(e.isDirectory()||!n.endsWith(".png")||!n.contains("buildingtile"))continue;byte[] d=read(z);Bitmap b=BitmapFactory.decodeByteArray(d,0,d.length);if(b!=null)pending.add(b);}}catch(Exception ignored){}}
 private byte[] read(ZipInputStream z)throws Exception{ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=z.read(b))>0)o.write(b,0,n);return o.toByteArray();}
 @Override public void onSurfaceCreated(GL10 gl,EGLConfig c){GLES20.glClearColor(.04f,.06f,.08f,1);GLES20.glEnable(GLES20.GL_DEPTH_TEST);pc=prog("attribute vec3 A;uniform mat4 M;void main(){gl_Position=M*vec4(A,1.);}","precision mediump float;uniform vec4 C;void main(){gl_FragColor=C;}");pt=prog("attribute vec3 A;attribute vec2 U;uniform mat4 M;varying vec2 T;void main(){T=U;gl_Position=M*vec4(A,1.);}","precision mediump float;uniform sampler2D S;varying vec2 T;void main(){gl_FragColor=texture2D(S,T);}");cp=GLES20.glGetAttribLocation(pc,"A");cc=GLES20.glGetUniformLocation(pc,"C");cm=GLES20.glGetUniformLocation(pc,"M");tp=GLES20.glGetAttribLocation(pt,"A");tu=GLES20.glGetAttribLocation(pt,"U");tm=GLES20.glGetUniformLocation(pt,"M");ts=GLES20.glGetUniformLocation(pt,"S");cube=buf(makeCube());quad=buf(new float[]{-1,-1,0,1,-1,0,1,1,0,-1,-1,0,1,1,0,-1,1,0});uv=buf(new float[]{0,1,1,1,1,0,0,1,1,0,0,0});for(Bitmap b:pending){int[] id=new int[1];GLES20.glGenTextures(1,id,0);GLES20.glBindTexture(GLES20.GL_TEXTURE_2D,id[0]);GLES20.glTexParameteri(GLES20.GL_TEXTURE_2D,GLES20.GL_TEXTURE_MIN_FILTER,GLES20.GL_LINEAR);GLES20.glTexParameteri(GLES20.GL_TEXTURE_2D,GLES20.GL_TEXTURE_MAG_FILTER,GLES20.GL_LINEAR);GLUtils.texImage2D(GLES20.GL_TEXTURE_2D,0,b,0);b.recycle();textures.add(id[0]);}pending.clear();}
 private float[] makeCube(){float[][] f={{-1,-1,1,1,-1,1,1,1,1,-1,-1,1,1,1,1,-1,1,1},{1,-1,-1,-1,-1,-1,-1,1,-1,1,-1,-1,-1,1,-1,1,1,-1},{-1,1,1,1,1,1,1,1,-1,-1,1,1,1,1,-1,-1,1,-1},{-1,-1,-1,1,-1,-1,1,-1,1,-1,-1,-1,1,-1,1,-1,-1,1},{1,-1,1,1,-1,-1,1,1,-1,1,-1,1,1,1,-1,1,1,1},{-1,-1,-1,-1,-1,1,-1,1,1,-1,-1,-1,-1,1,1,-1,1,-1}};float[] o=new float[108];int q=0;for(float[] a:f)for(float x:a)o[q++]=x;return o;}
 @Override public void onSurfaceChanged(GL10 g,int w,int h){GLES20.glViewport(0,0,w,h);Matrix.perspectiveM(p,0,60,(float)w/Math.max(1,h),.1f,180);}
 @Override public void onDrawFrame(GL10 g){float s=(float)Math.hypot(dx,dy);if(s>.1){px+=dx/s*4/60f;pz+=dy/s*4/60f;}float cx=px-(float)Math.sin(yaw)*11,cz=pz+(float)Math.cos(yaw)*11;Matrix.setLookAtM(v,0,cx,7,cz,px,1,pz,0,1,0);Matrix.multiplyMM(vp,0,p,0,v,0);GLES20.glClear(GLES20.GL_COLOR_BUFFER_BIT|GLES20.GL_DEPTH_BUFFER_BIT);box(0,-.2f,0,70,.4f,70,.25f,.22f,.18f);for(Building b:buildings){box(b.x,b.h/2,b.z,b.w,b.h,b.d,.4f,.31f,.22f);facade(b);}}
 private void box(float x,float y,float z,float w,float h,float d,float r,float g,float b){Matrix.setIdentityM(m,0);Matrix.translateM(m,0,x,y,z);Matrix.scaleM(m,0,w,h,d);Matrix.multiplyMM(mm,0,vp,0,m,0);GLES20.glUseProgram(pc);GLES20.glUniformMatrix4fv(cm,1,false,mm,0);GLES20.glUniform4f(cc,r,g,b,1);cube.position(0);GLES20.glEnableVertexAttribArray(cp);GLES20.glVertexAttribPointer(cp,3,GLES20.GL_FLOAT,false,0,cube);GLES20.glDrawArrays(GLES20.GL_TRIANGLES,0,36);GLES20.glDisableVertexAttribArray(cp);}
 private void facade(Building b){if(textures.isEmpty())return;int id=textures.get(b.panel%textures.size());face(id,b.x,b.z-b.d/2-.02f,b.w,b.h,0);face(id,b.x,b.z+b.d/2+.02f,b.w,b.h,180);face(id,b.x-b.w/2-.02f,b.z,b.d,b.h,90);face(id,b.x+b.w/2+.02f,b.z,b.d,b.h,-90);}private void face(int id,float x,float z,float w,float h,float rot){Matrix.setIdentityM(m,0);Matrix.translateM(m,0,x,h/2,z);Matrix.rotateM(m,0,rot,0,1,0);Matrix.scaleM(m,0,w/2,h/2,1);Matrix.multiplyMM(mm,0,vp,0,m,0);GLES20.glUseProgram(pt);GLES20.glUniformMatrix4fv(tm,1,false,mm,0);GLES20.glUniform1i(ts,0);GLES20.glBindTexture(GLES20.GL_TEXTURE_2D,id);quad.position(0);uv.position(0);GLES20.glEnableVertexAttribArray(tp);GLES20.glVertexAttribPointer(tp,3,GLES20.GL_FLOAT,false,0,quad);GLES20.glEnableVertexAttribArray(tu);GLES20.glVertexAttribPointer(tu,2,GLES20.GL_FLOAT,false,0,uv);GLES20.glDrawArrays(GLES20.GL_TRIANGLES,0,6);GLES20.glDisableVertexAttribArray(tp);GLES20.glDisableVertexAttribArray(tu);}
 public boolean onTouch(MotionEvent e){float x=e.getX();if(e.getActionMasked()==MotionEvent.ACTION_DOWN){lx=x;move=x<900;return true;}if(e.getActionMasked()==MotionEvent.ACTION_MOVE){if(move){dx=Math.max(-1,Math.min(1,(x-lx)/120));dy=Math.max(-1,Math.min(1,e.getY()/120));}else yaw+=(x-lx)*.004f;lx=x;return true;}if(e.getActionMasked()==MotionEvent.ACTION_UP||e.getActionMasked()==MotionEvent.ACTION_CANCEL){dx=dy=0;move=false;}return true;}
 public void pause(){}public void resume(){}
 private int prog(String v,String f){int a=sh(GLES20.GL_VERTEX_SHADER,v),b=sh(GLES20.GL_FRAGMENT_SHADER,f),q=GLES20.glCreateProgram();GLES20.glAttachShader(q,a);GLES20.glAttachShader(q,b);GLES20.glLinkProgram(q);return q;}private int sh(int t,String s){int q=GLES20.glCreateShader(t);GLES20.glShaderSource(q,s);GLES20.glCompileShader(q);return q;}private static FloatBuffer buf(float[] a){FloatBuffer b=ByteBuffer.allocateDirect(a.length*4).order(ByteOrder.nativeOrder()).asFloatBuffer();b.put(a).position(0);return b;}private static final class Building{final float x,z,w,d,h;final int panel;Building(float x,float z,float w,float d,float h,int p){this.x=x;this.z=z;this.w=w;this.d=d;this.h=h;this.panel=p;}}
}
