package com.persiawar2d;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.opengl.GLES20;
import android.opengl.GLSurfaceView;
import android.opengl.GLUtils;
import android.opengl.Matrix;
import android.view.MotionEvent;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.FloatBuffer;
import java.util.ArrayList;
import java.util.Random;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

/** Playable 3D vertical slice using the project's existing building panels as textures. */
public final class AdvancedThreeDRenderer implements GLSurfaceView.Renderer {
    private final Context ctx; private final Random rnd=new Random(91);
    private final float[] p=new float[16],v=new float[16],vp=new float[16],m=new float[16],mvp=new float[16];
    private final ArrayList<Building> buildings=new ArrayList<>(); private final ArrayList<Enemy> enemies=new ArrayList<>(); private final ArrayList<Integer> textures=new ArrayList<>();
    private FloatBuffer cube,uv; private int colorProg,texProg,aPos,aNor,uMvp,uModel,uColor,uLight,tPos,tUv,tMvp,tTex,tColor; private long last;
    private float px=0,pz=18,yaw=0,moveX,moveY,lastX,lastY; private boolean moveTouch; private int hp=100,ammo=30,kills=0; private float fireCooldown=0;

    public AdvancedThreeDRenderer(Context c){ctx=c; loadPanels(); buildCity();}
    private void loadPanels(){try(InputStream raw=ctx.getAssets().open("original_packages/kenney_isometric-buildings.zip");ZipInputStream z=new ZipInputStream(raw)){ZipEntry e;while((e=z.getNextEntry())!=null&&textures.size()<20){String n=e.getName().toLowerCase();if(e.isDirectory()||!n.endsWith(".png")||!n.contains("buildingtile"))continue;int id=tileId(n);if(id<32)continue;byte[] b=read(z);Bitmap bm=BitmapFactory.decodeByteArray(b,0,b.length);if(bm!=null&&bm.getWidth()>=48&&bm.getHeight()>=48){panelBitmaps.add(b);}}}catch(Exception ignored){}}
    private final ArrayList<byte[]> panelBitmaps=new ArrayList<>();
    private int tileId(String n){try{int u=n.lastIndexOf('_'),d=n.lastIndexOf('.');return Integer.parseInt(n.substring(u+1,d));}catch(Exception e){return -1;}}
    private byte[] read(ZipInputStream z)throws Exception{ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=z.read(b))>0)o.write(b,0,n);return o.toByteArray();}
    private void buildCity(){for(int z=-30;z<=30;z+=10)for(int x=-30;x<=30;x+=10){if(Math.abs(x)<8&&Math.abs(z)<8)continue;buildings.add(new Building(x,z,5+rnd.nextInt(4),5+rnd.nextInt(4),buildings.size()));}for(int i=0;i<10;i++){double a=i*Math.PI*2/10;enemies.add(new Enemy((float)Math.cos(a)*15,(float)Math.sin(a)*15));}}
    @Override public void onSurfaceCreated(javax.microedition.khronos.egl.EGLConfig c){GLES20.glClearColor(.045f,.065f,.085f,1);GLES20.glEnable(GLES20.GL_DEPTH_TEST);GLES20.glEnable(GLES20.GL_CULL_FACE);colorProg=program("attribute vec3 a;attribute vec3 n;uniform mat4 M,N;varying vec3 L;void main(){L=mat3(N)*n;gl_Position=M*vec4(a,1.);}","precision mediump float;uniform vec3 C,L0;varying vec3 L;void main(){float x=.35+.65*max(dot(normalize(L),normalize(L0)),0.);gl_FragColor=vec4(C*x,1.);}");texProg=program("attribute vec3 a;attribute vec2 t;uniform mat4 M;varying vec2 T;void main(){T=t;gl_Position=M*vec4(a,1.);}","precision mediump float;uniform sampler2D S;varying vec2 T;void main(){gl_FragColor=texture2D(S,T);}");aPos=GLES20.glGetAttribLocation(colorProg,"a");aNor=GLES20.glGetAttribLocation(colorProg,"n");uMvp=GLES20.glGetUniformLocation(colorProg,"M");uModel=GLES20.glGetUniformLocation(colorProg,"N");uColor=GLES20.glGetUniformLocation(colorProg,"C");uLight=GLES20.glGetUniformLocation(colorProg,"L0");tPos=GLES20.glGetAttribLocation(texProg,"a");tUv=GLES20.glGetAttribLocation(texProg,"t");tMvp=GLES20.glGetUniformLocation(texProg,"M");tTex=GLES20.glGetUniformLocation(texProg,"S");cube=buf(new float[]{-1,-1,1,1,-1,1,1,1,1,-1,-1,1,1,1,1,-1,1,1,-1,-1,-1,-1,1,-1,1,1,-1,-1,-1,-1,1,1,-1,1,1,-1});uv=buf(new float[]{0,1,1,1,1,0,0,1,1,0,0,0});for(byte[] b:panelBitmaps){Bitmap bm=BitmapFactory.decodeByteArray(b,0,b.length);int[] q=new int[1];GLES20.glGenTextures(1,q,0);GLES20.glBindTexture(GLES20.GL_TEXTURE_2D,q[0]);GLES20.glTexParameteri(GLES20.GL_TEXTURE_2D,GLES20.GL_TEXTURE_MIN_FILTER,GLES20.GL_LINEAR);GLES20.glTexParameteri(GLES20.GL_TEXTURE_2D,GLES20.GL_TEXTURE_MAG_FILTER,GLES20.GL_LINEAR);GLES20.glTexParameteri(GLES20.GL_TEXTURE_2D,GLES20.GL_TEXTURE_WRAP_S,GLES20.GL_CLAMP_TO_EDGE);GLES20.glTexParameteri(GLES20.GL_TEXTURE_2D,GLES20.GL_TEXTURE_WRAP_T,GLES20.GL_CLAMP_TO_EDGE);GLUtils.texImage2D(GLES20.GL_TEXTURE_2D,0,bm,0);bm.recycle();textures.add(q[0]);}last=System.nanoTime();}
    @Override public void onSurfaceChanged(javax.microedition.khronos.opengles.GL10 g,int w,int h){GLES20.glViewport(0,0,w,h);Matrix.perspectiveM(p,0,60,(float)w/Math.max(1,h),.1f,160);}
    @Override public void onDrawFrame(javax.microedition.khronos.opengles.GL10 g){float dt=Math.min(.05f,(System.nanoTime()-last)/1e9f);last=System.nanoTime();fireCooldown-=dt;updatePlayer(dt);updateEnemies(dt);float cx=px-(float)Math.sin(yaw)*11,cz=pz+(float)Math.cos(yaw)*11;Matrix.setLookAtM(v,0,cx,7,cz,px,1,pz,0,1,0);Matrix.multiplyMM(vp,0,p,0,v,0);GLES20.glClear(GLES20.GL_COLOR_BUFFER_BIT|GLES20.GL_DEPTH_BUFFER_BIT);GLES20.glUseProgram(colorProg);GLES20.glUniform3f(uLight,-.4f,1,.3f);drawBox(0,-.2f,0,70,.4f,70,new float[]{.28f,.25f,.20f});for(int x=-60;x<=60;x+=5)drawBox(x,.01f,0,.025f,.02f,65,new float[]{.38f,.34f,.27f});for(Building b:buildings){drawBox(b.x,b.h/2,b.z,b.w,b.h,b.d,new float[]{.43f,.33f,.23f});drawFacade(b);}for(Enemy e:enemies)if(e.hp>0)drawBox(e.x,1,e.z,1.2f,2,1.2f,new float[]{.55f,.10f,.08f});drawBox(px,1,pz,1.1f,2,1.1f,new float[]{.20f,.52f,.76f});}
    private void updatePlayer(float dt){float l=(float)Math.hypot(moveX,moveY);if(l>.1f){float nx=px+moveX/l*5*dt,nz=pz+moveY/l*5*dt;if(!blocked(nx,pz,1))px=nx;if(!blocked(px,nz,1))pz=nz;}}
    private void updateEnemies(float dt){for(Enemy e:enemies)if(e.hp>0){float dx=px-e.x,dz=pz-e.z,d=(float)Math.hypot(dx,dz);if(d>1.7f){float nx=e.x+dx/d*1.2f*dt,nz=e.z+dz/d*1.2f*dt;if(!blocked(nx,e.z,.7f))e.x=nx;if(!blocked(e.x,nz,.7f))e.z=nz;}else hp=Math.max(0,hp-(int)(12*dt));}}
    private boolean blocked(float x,float z,float r){for(Building b:buildings)if(x>b.x-b.w/2-r&&x<b.x+b.w/2+r&&z>b.z-b.d/2-r&&z<b.z+b.d/2+r)return true;return x<-65||x>65||z<-65||z>65;}
    private void shoot(){if(fireCooldown>0||ammo<=0)return;fireCooldown=.18f;ammo--;float sx=(float)Math.sin(yaw),sz=(float)-Math.cos(yaw);Enemy best=null;float bd=999;for(Enemy e:enemies)if(e.hp>0){float dx=e.x-px,dz=e.z-pz,d=(float)Math.hypot(dx,dz),dot=(dx*sx+dz*sz)/Math.max(d,.01f);if(dot>.93f&&d<25&&d<bd){bd=d;best=e;}}if(best!=null){best.hp-=40;if(best.hp<=0)kills++;}}
    private void drawFacade(Building b){if(textures.isEmpty())return;int id=textures.get(b.panel%textures.size());GLES20.glUseProgram(texProg);GLES20.glUniform1i(tTex,0);GLES20.glActiveTexture(GLES20.GL_TEXTURE0);GLES20.glBindTexture(GLES20.GL_TEXTURE_2D,id);facade(b.x,b.z-b.d/2-.01f,b.w,b.h,0);facade(b.x,b.z+b.d/2+.01f,b.w,b.h,1);}
    private void facade(float x,float z,float w,float h,int side){Matrix.setIdentityM(m,0);Matrix.translateM(m,0,x,h/2,z);if(side==1)Matrix.rotateM(m,0,180,0,1,0);Matrix.scaleM(m,0,w/2,h/2,1);Matrix.multiplyMM(mvp,0,vp,0,m,0);GLES20.glUniformMatrix4fv(tMvp,1,false,mvp,0);cube.position(0);uv.position(0);GLES20.glEnableVertexAttribArray(tPos);GLES20.glVertexAttribPointer(tPos,3,GLES20.GL_FLOAT,false,0,cube);GLES20.glEnableVertexAttribArray(tUv);GLES20.glVertexAttribPointer(tUv,2,GLES20.GL_FLOAT,false,0,uv);GLES20.glDrawArrays(GLES20.GL_TRIANGLES,0,6);GLES20.glDisableVertexAttribArray(tPos);GLES20.glDisableVertexAttribArray(tUv);}
    private void drawBox(float x,float y,float z,float w,float h,float d,float[] c){Matrix.setIdentityM(m,0);Matrix.translateM(m,0,x,y,z);Matrix.scaleM(m,0,w,h,d);Matrix.multiplyMM(mvp,0,vp,0,m,0);GLES20.glUseProgram(colorProg);GLES20.glUniformMatrix4fv(uMvp,1,false,mvp,0);GLES20.glUniformMatrix4fv(uModel,1,false,m,0);GLES20.glUniform3fv(uColor,1,c,0);cube.position(0);GLES20.glEnableVertexAttribArray(aPos);GLES20.glVertexAttribPointer(aPos,3,GLES20.GL_FLOAT,false,0,cube);GLES20.glEnableVertexAttribArray(aNor);GLES20.glVertexAttribPointer(aNor,3,GLES20.GL_FLOAT,false,0,cube);GLES20.glDrawArrays(GLES20.GL_TRIANGLES,0,6);GLES20.glDisableVertexAttribArray(aPos);GLES20.glDisableVertexAttribArray(aNor);}
    public boolean onTouch(MotionEvent e){float x=e.getX(),y=e.getY();if(e.getActionMasked()==MotionEvent.ACTION_DOWN){lastX=x;lastY=y;moveTouch=x<900;if(!moveTouch)shoot();setMove(x,y);return true;}if(e.getActionMasked()==MotionEvent.ACTION_MOVE){if(moveTouch)setMove(x,y);else yaw+=(x-lastX)*.004f;lastX=x;return true;}if(e.getActionMasked()==MotionEvent.ACTION_UP||e.getActionMasked()==MotionEvent.ACTION_CANCEL){moveX=moveY=0;moveTouch=false;}return true;}
    private void setMove(float x,float y){moveX=Math.max(-1,Math.min(1,(x-lastX)/120));moveY=Math.max(-1,Math.min(1,(y-lastY)/120));}
    public int getHp(){return hp;}public int getAmmo(){return ammo;}public int getKills(){return kills;}public void pause(){}public void resume(){}
    private int program(String vs,String fs){return link(vs,fs);}private int link(String a,String b){int x=shader(GLES20.GL_VERTEX_SHADER,a),y=shader(GLES20.GL_FRAGMENT_SHADER,b),q=GLES20.glCreateProgram();GLES20.glAttachShader(q,x);GLES20.glAttachShader(q,y);GLES20.glLinkProgram(q);return q;}private int shader(int t,String s){int q=GLES20.glCreateShader(t);GLES20.glShaderSource(q,s);GLES20.glCompileShader(q);return q;}private static FloatBuffer buf(float[] a){FloatBuffer b=ByteBuffer.allocateDirect(a.length*4).order(ByteOrder.nativeOrder()).asFloatBuffer();b.put(a).position(0);return b;}
    private static final class Building{final float x,z,w,d,h;final int panel;Building(float x,float z,float w,float d,int p){this.x=x;this.z=z;this.w=w;this.d=d;this.h=2.5f+(p%4)*.7f;this.panel=p;}}private static final class Enemy{float x,z,hp=100;Enemy(float x,float z){this.x=x;this.z=z;}}
}
